### PR TITLE
just a suggestion

### PR DESCRIPTION
**Pull request by Mephiztopheles**
Things that should be written in a diferent way in my opinion

### CODE REVIEW

**Comment by ckelsey** [comment]
Hi, thanks for checking out the code.

I'm curious why you would use {{}} instead of ngStyle as its my understanding that {{}} updates every digest and ngStyle updates only when the model changes. I've also had issues with IE10 and {{}} on a style attribute not updating before so I just stopped using it. Please let me know, thanks!

**Comment by Mephiztopheles** [comment]
i answered per mail.... doesn't show up here -.-

**Comment by Mephiztopheles** [comment]
Some Browsers don't support angular expression in attributes. Not just the angular notation in text-nodes but also the ones in attributes will be checked in events cycle which is reachable from the owning scope. Let's say you have scope id 1 as app scope and 2 childscopes. When something was changed in the child scope 1 the child scope 2 will not be processed in case it was not a property which is accessible in cs2 
But ng-style don't need so much power than to process like 6 notations every digest and add the string values which were not in the expression ☺ 
I'm working in a company where I build a front end of a crm with angular. If you have any question feel free to ask 
Oh yea... I fogott... I saw some bugs in your color wheel I can tell ya if you want to 😆

**Comment by ckelsey** [comment]
Haha, my mistake, I read your pr wrong. I thought I was using ngStyle. Your absolutely right, ngStyle is the correct way. Thanks for catching that. Any other bugs, for sure let me know. Thanks again for the feedback!

**Pull request merged**
